version: 2

project_name: chamber

before:
  hooks:
    - go mod download

builds:
  - main: cmd/chamber/main.go
    ldflags: >
      -X github.com/cirruslabs/chamber/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/chamber/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED={{if eq .Os "darwin"}}1{{else}}0{{end}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    formats: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

homebrew_casks:
  - name: chamber
    ids:
      - regular
    repository:
      owner: cirruslabs
      name: homebrew-cli
    license: AGPLv3
    dependencies:
      - formula: "cirruslabs/cli/tart"
    caveats: See the Github repository for more information

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"